---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(p8105.datasets)
library(plotly)
library(tidyverse)
library(dplyr)

data("instacart")

select_instacart = 
  instacart |> 
  as_tibble() |> 
  filter(
    department == "frozen"
  ) |> 
  select(order_hour_of_day, aisle,order_dow, 
         order_number, reordered)

```

Column {data-width=450}
-----------------------------------------------------------------------

### Chart A

```{r}

select_instacart |> 
  filter(order_dow == 1) |> 
     plot_ly(y = ~order_hour_of_day, color = ~aisle,
          type = "box", colors = "viridis") |> 
    layout(
    title = "Order Hours of Day on Monday Based on Aisle in Frozen Department",
    yaxis = list(title = "Order Hours of Day")
  )

```

Column {data-width=450}
-----------------------------------------------------------------------

### Chart B

```{r}
select_instacart |> 
  group_by(order_dow) |> 
  summarize(avg_reorder_rate = mean(reordered)) |> 
  plot_ly(x = ~order_dow, y = ~avg_reorder_rate, type = 'scatter', mode = 'lines+markers') |> 
  layout(
    title = "Average Reorder Rate by Day of the Week",
    xaxis = list(title = "Day of the Week"),
    yaxis = list(title = "Average Reorder Rate")
  )
```

### Chart C

```{r}
select_instacart |> 
  count(aisle) |> 
  mutate(aisle = fct_reorder(aisle, n)) |> 
  plot_ly(x = ~aisle, y = ~n, type = "bar", color = ~aisle) |> 
    layout(
    title = "Numbers of Aisle in Frozen Department",
    xaxis = list(title = "Asile"),
    yaxis = list(title = "Numbers of Aisle")
  )

```

